Remove request assignation
Fixes
```
TypeError: Cannot set property request of #<Socket> which has only a getter
    at new Socket (/Users/andral/Dev/web/42_bitcoin/lib/red-bridge/node_modules/socket.io/lib/socket.js:63:16)
    at Namespace.add (/Users/andral/Dev/web/42_bitcoin/lib/red-bridge/node_modules/socket.io/lib/namespace.js:156:16)
    at Client.connect (/Users/andral/Dev/web/42_bitcoin/lib/red-bridge/node_modules/socket.io/lib/client.js:74:20)
    at Server.onconnection (/Users/andral/Dev/web/42_bitcoin/lib/red-bridge/node_modules/socket.io/lib/index.js:318:10)
    at emitOne (events.js:77:13)
    at Server.emit (events.js:169:7)
```
in strict mode.